"""add unique constraint for tenant email

Revision ID: 0e09cb8bd42c
Revises: 3d7a2ffeabe1
Create Date: 2026-03-25 07:31:38.731469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e09cb8bd42c'
down_revision: Union[str, Sequence[str], None] = '3d7a2ffeabe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tenant_email', 'users', ['tenant_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_email', 'users', type_='unique')
    # ### end Alembic commands ###
