"""Update seed models with correct fields

Revision ID: 19d4b48921ba
Revises: a70f11b11a20
Create Date: 2026-03-09 20:30:28.832258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19d4b48921ba'
down_revision: Union[str, Sequence[str], None] = 'a70f11b11a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('customers', sa.Column('country', sa.String(length=100), nullable=False))
    op.drop_column('customers', 'name')
    op.add_column('plans', sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('plans', sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('plans', sa.Column('max_seats', sa.Integer(), nullable=False))
    op.drop_column('plans', 'description')
    op.drop_column('plans', 'price')
    op.drop_column('plans', 'billing_period')
    op.add_column('subscriptions', sa.Column('billing_cycle', sa.String(length=20), nullable=False))
    op.add_column('subscriptions', sa.Column('seats', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'started_at')
    op.drop_column('subscriptions', 'seats')
    op.drop_column('subscriptions', 'billing_cycle')
    op.add_column('plans', sa.Column('billing_period', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('plans', 'max_seats')
    op.drop_column('plans', 'price_yearly')
    op.drop_column('plans', 'price_monthly')
    op.add_column('customers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'company_name')
    # ### end Alembic commands ###
