"""add features to plan and cancelled_at trial_ends_at to subscription

Revision ID: 4557ab7c1468
Revises: 56775600684f
Create Date: 2026-03-14 08:45:42.030254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4557ab7c1468'
down_revision: Union[str, Sequence[str], None] = '56775600684f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dead_letter_queue', 'created_at')
    op.drop_column('dead_letter_queue', 'updated_at')
    op.add_column('plans', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_jobs_created', 'report_jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_status', 'report_jobs', ['status'], unique=False)
    op.create_index('idx_jobs_tenant', 'report_jobs', ['tenant_id'], unique=False)
    op.create_index('idx_jobs_user', 'report_jobs', ['user_id'], unique=False)
    op.create_unique_constraint('uq_jobs_tenant_idempotency', 'report_jobs', ['tenant_id', 'idempotency_key'])
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('trial_ends_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'trial_ends_at')
    op.drop_column('subscriptions', 'cancelled_at')
    op.drop_constraint('uq_jobs_tenant_idempotency', 'report_jobs', type_='unique')
    op.drop_index('idx_jobs_user', table_name='report_jobs')
    op.drop_index('idx_jobs_tenant', table_name='report_jobs')
    op.drop_index('idx_jobs_status', table_name='report_jobs')
    op.drop_index('idx_jobs_created', table_name='report_jobs')
    op.drop_column('plans', 'features')
    op.add_column('dead_letter_queue', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('dead_letter_queue', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
