"""Add dead_letter_queue table

Revision ID: 56775600684f
Revises: 19d4b48921ba
Create Date: 2026-03-12 14:12:45.762981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56775600684f'
down_revision: Union[str, Sequence[str], None] = '19d4b48921ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_queue',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('error_trace', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('last_error_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['report_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_queue_job_id'), 'dead_letter_queue', ['job_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_queue_resolved'), 'dead_letter_queue', ['resolved'], unique=False)
    op.create_index(op.f('ix_dead_letter_queue_tenant_id'), 'dead_letter_queue', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letter_queue_tenant_id'), table_name='dead_letter_queue')
    op.drop_index(op.f('ix_dead_letter_queue_resolved'), table_name='dead_letter_queue')
    op.drop_index(op.f('ix_dead_letter_queue_job_id'), table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    # ### end Alembic commands ###
